name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DB_PATH: ./db.sqlite

jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn lint
    - run: yarn update-env
    - run: yarn test
